# 13 Numpy et Broadcasting

Une façon de numpy a été construire des calculs de tableaux de façon très rapide et simple 
Le rectangle A et B de même dimension ou égal 1 : 
Lorsque l’on travaille dans une dimension complète (3, ), il est possible de faire le broadcasting, car on considère 3 comme le dernier élément. 

In [0]:
import numpy as np

In [3]:
A = np.ones((2, 3))
B = 3
print(A+B) # résultat 1
 
A = np.ones((2, 3))
B = np.ones((2, 1)) # B a une colonne, elle sera étendu sur les trois colonnes de A
print(A+B) # résultat 2
 
A = np.ones((2, 3))
B = np.ones((2, 2))


[[4. 4. 4.]
 [4. 4. 4.]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [1]:
import numpy as np

In [2]:
A = np.ones((2, 3))
B = np.ones((2, 1))

In [3]:
A

array([[1., 1., 1.],
       [1., 1., 1.]])